//
//  CoordinatePresenter.swift
//  Waasdu
//
//  Created by Алексей on 15.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol CoordinatePresentationLogic {
    func presentSomething(response: Coordinate.Response)
    func presentCircle(response: Coordinate.Response)
}

class CoordinatePresenter: CoordinatePresentationLogic {
    weak var viewController: CoordinateDisplayLogic?

    // MARK: Do something

    func presentSomething(response: Coordinate.Response) {
//        let viewModel = Coordinate.Something.ViewModel()
//        viewController?.displaySomething(viewModel: viewModel)
    }
    
    func presentCircle(response: Coordinate.Response) {
        let center = CLLocationCoordinate2D(latitude: response.circleCoordinates[0], longitude: response.circleCoordinates[1])
        let radius = response.circleRadius
        let viewModel = Coordinate.ViewModel(
            circle: MKCircle(
                center: center,
                radius: radius
            )
        )
        viewController?.displayCircle(viewModel: viewModel)
    }
}
