//
//  CoordinatePresenter.swift
//  Waasdu
//
//  Created by Алексей on 15.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

protocol CoordinatePresentationLogic {
    func presentCircle(response: Coordinate.Response)
    func presentDistance(response: Coordinate.Response.ResponseType.Distance)
    func presentLines(response: Coordinate.Response.ResponseType.Coordinats)
}

class CoordinatePresenter: CoordinatePresentationLogic {
    weak var viewController: CoordinateDisplayLogic?
    
    // Преобразуем числа в координаты для отображения
    func presentCircle(response: Coordinate.Response) {
        let center = CLLocationCoordinate2D(latitude: response.circleCoordinates[0], longitude: response.circleCoordinates[1])
        let radius = response.circleRadius
        let viewModel = Coordinate.ViewModel.Element.Circle(
            params: MKCircle(
                center: center,
                radius: radius
            )
        )
        viewController?.displayCircle(viewModel: viewModel)
    }
    // Преобразуем числа в координаты для отображения
    func presentLines(response: Coordinate.Response.ResponseType.Coordinats) {
        var result: [MKPolyline] = []
        for res in response.params {
            //Преобразуем double в координаты
            let coord = res[0].map {
                CLLocationCoordinate2D(
                    latitude: $0[1],
                    longitude: $0[0])
            }
            // Создаем линию по координатам
            var line = MKPolyline(coordinates: coord, count: coord.count)
            //Проверяем пересекает ли линия 180 меридиан
            if line.boundingMapRect.spans180thMeridian{
                //Если да, то пытаемся поправить
                let re = coord.map{
                    CLLocationCoordinate2D(
                        latitude: $0.latitude,
                        longitude: calc(number: $0.longitude)
                    )
                }
                line = MKPolyline(coordinates: re, count: re.count)
            }
            result.append(line)
        }
        //Отправляем данные для отображения
        let viewModel = Coordinate.ViewModel.Element.Lines(params: result)
        viewController?.displayLines(viewModel: viewModel)
    }
    
    func presentDistance(response: Coordinate.Response.ResponseType.Distance) {
        let distance = Int(response.value / 1000)
        let result = String("Длина: \(distance) км")
        let viewModel = Coordinate.ViewModel.Element.Distance(value: result)
        viewController?.updateLabel(viewModel: viewModel)
    }
    
    // Меняем долготу, если она превышает границы
    private func calc (number: Double) -> Double {
        if number > 180 {
            return number - 360
        } else if number < -180 {
            return number + 360
        } else {
            return number
        }
    }
}
