//
//  CoordinateModels.swift
//  Waasdu
//
//  Created by Алексей on 15.05.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import MapKit

enum Coordinate{
    // MARK: Use cases
    
    struct Request{
        enum RequestType {
            struct GetCircle {
                var coordinats: CLLocationCoordinate2D
            }
        }
        var circleCoordinates: [Double]?
        var circleRadius: Double?
    }
    struct Response{
        enum ResponseType {
            struct Circle {
                var circleCoordinates: [Double]
                var circleRadius: Double
            }
            
            struct Coordinats {
                var params: [[[[Double]]]]
            }
        }
        var circleCoordinates: [Double]
        var circleRadius: Double
    }
    struct ViewModel{
        enum Element {
            
            struct Circle {
                var params: MKCircle
            }
            
            struct Lines {
                var params: [MKPolyline]
            }
            struct Polygons {
                var myltiPolygon: MKMultiPolygon
            }
        }
    }
}
